### PR TITLE
fix pr reviews

### LINKED ISSUE #15: Fix PR reviews

### PR DESCRIPTION
**Pull request by abhishekt98**
Fixes #15

### CODE REVIEW

File: app/javascript/src/components/notes/AddNote.jsx [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+            </Pane.Header>
+            <Pane.Body>
+              <div className="w-full space-y-6">
+                <Input label="Title" name="title" size="large" required />
+
+                <Textarea
+                  label="Description"
+                  name="description"
+                  rows={2}
+                  required
```
Comment (karthiknmenon) [inline app/javascript/src/components/notes/AddNote.jsx:42]: We don't need required here.

File: app/javascript/src/components/notes/AddNote.jsx [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+                />
+
+                <Select
+                  name="contact"
+                  label="Assigned Contact"
+                  placeholder="Select Role"
+                  required
```
Comment (karthiknmenon) [inline app/javascript/src/components/notes/AddNote.jsx:49]: We don't need required here.

File: app/javascript/src/components/notes/AddNote.jsx [hunk 3]
```diff
@@ -0,0 +1,93 @@
...
+                  options={ASSIGNED_CONTACT_SELECT_OPTIONS}
+                />
+
+                <Select
+                  name="tags"
+                  label="Tags"
+                  placeholder="Select Tags"
+                  options={TAG_SELECT_OPTIONS}
+                  required
```
Comment (karthiknmenon) [inline app/javascript/src/components/notes/AddNote.jsx:58]: We don't need required here.

**Review by karthiknmenon — COMMENTED** [review]
@abhishekt98 Please check. Few small suggestions.

File: app/javascript/src/components/common/SideMenuBar.jsx [hunk 4]
```diff
@@ -1,20 +1,19 @@
 import React, { useState } from "react";
 
-import { Search, Settings, Plus } from "@bigbinary/neeto-icons";
+import { Search, Settings, Plus } from "neetoIcons";
 import { Typography } from "neetoui/v2";
 import { MenuBar } from "neetoui/v2/layouts";
 
-const ContactMenubar = ({ title }) => {
+const SideMenuBar = ({ title, blocks }) => {
```
[the remark this answers is not in the document]
Comment (abhishekt98) [reply app/javascript/src/components/common/SideMenuBar.jsx:7]: We can't use `MenuBar` since the neeto component also has the same name.

File: app/javascript/src/components/contacts/AddContact.jsx [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+              />
+            </Pane.Footer>
+          </Form>
+        )}
+      </Formik>
+    </Pane>
+  );
+};
+
+export default Addcontact;
```
[the remark this answers is not in the document]
Comment (abhishekt98) [reply app/javascript/src/components/contacts/AddContact.jsx]: I actually renamed it locally  but changes are not reflected in github.
